import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def generate_pdf_report(scan_id, patient_id, results_dict, save_path):
    """
    Generates a PDF report containing the MRI scan results, confidence, 
    and recommendations. Saves it to `save_path`.
    """
    try:
        # We ensure the directory exists just in case
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        
        c = canvas.Canvas(save_path, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, "VaidhyaNetra AI - MRI Analysis Report")
        
        # Patient Info
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 90, f"Patient ID: {patient_id}")
        c.drawString(50, height - 110, f"Scan ID: {scan_id}")
        # Placeholder for date
        from datetime import datetime
        c.drawString(50, height - 130, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        # Line separator
        c.line(50, height - 140, width - 50, height - 140)
        
        # Results
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 170, "Analysis Results:")
        
        c.setFont("Helvetica", 12)
        y_pos = height - 200
        
        tumor_detected = results_dict.get("tumor_detected", False)
        c.drawString(50, y_pos, f"Tumor Detected: {'YES' if tumor_detected else 'NO'}")
        
        if tumor_detected:
            c.setFillColor(colors.red)
            c.drawString(250, y_pos, f"*** {results_dict.get('severity_indicator', 'N/A')} SEVERITY ***")
            c.setFillColor(colors.black)
            
        y_pos -= 25
        c.drawString(50, y_pos, f"AI Confidence Score: {results_dict.get('confidence', 0) * 100:.2f}%")
        
        y_pos -= 25
        c.drawString(50, y_pos, f"Estimated Tumor Size: {results_dict.get('tumor_size', 0)} mm²")
        
        y_pos -= 25
        uncertainty = results_dict.get('uncertainty', {}).get('uncertainty_score', 0)
        c.drawString(50, y_pos, f"Model Uncertainty: {uncertainty:.4f}")
        
        # Growth Trend
        y_pos -= 40
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y_pos, "Longitudinal Tracker:")
        y_pos -= 20
        c.setFont("Helvetica", 12)
        c.drawString(50, y_pos, f"Trend: {results_dict.get('growth_trend', 'N/A')}")
        
        # Recommendation
        y_pos -= 40
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y_pos, "Clinical Recommendation:")
        y_pos -= 20
        c.setFont("Helvetica", 11)
        
        # Simple text wrapping logic for recommendation
        import textwrap
        rec_text = results_dict.get('recommendation', 'No recommendation generated.')
        wrapped_text = textwrap.wrap(rec_text, width=80)
        
        for line in wrapped_text:
            c.drawString(50, y_pos, line)
            y_pos -= 15
        
        # Add notes about images
        y_pos -= 40
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(50, y_pos, f"Note: MRI Source Imagery and Heatmap/Grad-CAM visual references are available")
        y_pos -= 15
        c.drawString(50, y_pos, f"in the patient portal or via Cloudinary direct links.")
        
        # Footer
        c.setFont("Helvetica", 8)
        c.drawString(50, 50, "Disclaimer: This report is generated by VaidhyaNetra AI and should be reviewed by a certified medical professional.")
        
        c.save()
        return save_path
        
    except Exception as e:
        print(f"Error generating PDF: {e}")
        return None
